// -- testcase1 --

s1("x11").
s1("x12").
s1("common_x1").
s1("common_x2").

s2("x21").
s2("x22").
s2("common_x1").
s2("common_x2").

// Expected view

// v("x11").
// v("x12").
// v("x21").
// v("x22").
// v("common_x1").
// v("common_x2").

v_prime("x11").
v_prime("x21").
v_prime("x22").
v_prime("common_x2").
v_prime("new").

// Expected source prime

// s1_prime("x11").
// s1_prime("common_x2").
// s1_prime("new").


// s2_prime("x21").
// s2_prime("x22").
// s1_prime("common_x2").
